// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowProject
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Registration By example Specflow feature", Description="\tThis functionality covers tests for registration with construction online websit" +
        "e by example keyword", SourceFile="RegistrationFeatureByExample.feature", SourceLine=0)]
    public partial class RegistrationByExampleSpecflowFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RegistrationFeatureByExample.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Registration By example Specflow feature", "\tThis functionality covers tests for registration with construction online websit" +
                    "e by example keyword", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void ChooseYourPlanByDifferentCombinations(string organization, string buisness, string personnel, string annualTurnover, string memberShipLevel, string acclaimStatus, string acclaimDeemedToSatisfy, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Choose Your plan by different combinations", null, exampleTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 6
testRunner.Given("Construction online home page is launched", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.And("Register Now link is being displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When("Click on Register now link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("Verify that it takes to the sign up for contruction page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.When("Plan selection page is displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.And(string.Format("Select your type of Buisness as {0}", organization), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And(string.Format("Select your type as {0}", buisness), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.And(string.Format("Enter your No of personnel as {0}", personnel), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.And(string.Format("Select your annual turnover as {0}", annualTurnover), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.And(string.Format("Select your membership as {0}", memberShipLevel), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.And(string.Format("If plan is silver then Add or remove accliam accredition to service {0}", acclaimStatus), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And(string.Format("If plan is gold then choose deemed to satisfy or Acclaim {0}", acclaimDeemedToSatisfy), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.When("Click on your details link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("Verify that your details page is being displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Choose Your plan by different combinations, Variant 0", SourceLine=22)]
        public virtual void ChooseYourPlanByDifferentCombinations_Variant0()
        {
#line 5
this.ChooseYourPlanByDifferentCombinations("I am a supplier", "Contractor", "50", "£100,000 - £199,999", "Silver", "True", "\"\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Choose Your plan by different combinations, Variant 1", SourceLine=22)]
        public virtual void ChooseYourPlanByDifferentCombinations_Variant1()
        {
#line 5
this.ChooseYourPlanByDifferentCombinations("I am a supplier", "Consultant", "70", "£350,000 - £699,999", "Associate", "\"\"", "\"\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Choose Your plan by different combinations, Variant 2", SourceLine=22)]
        public virtual void ChooseYourPlanByDifferentCombinations_Variant2()
        {
#line 5
this.ChooseYourPlanByDifferentCombinations("I am a supplier", "Materials Supplier", "90", "£6,000,000 - £9,999,999", "Platinum", "\"\"", "\"\"", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Choose Your plan by different combinations, Variant 3", SourceLine=22)]
        public virtual void ChooseYourPlanByDifferentCombinations_Variant3()
        {
#line 5
this.ChooseYourPlanByDifferentCombinations("I am a supplier", "Contractor", "30", "£1,500,000 - £2,499,999", "Gold", "\"\"", "Deemed To Satisfy", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Choose Your plan by different combinations, Variant 4", SourceLine=22)]
        public virtual void ChooseYourPlanByDifferentCombinations_Variant4()
        {
#line 5
this.ChooseYourPlanByDifferentCombinations("I am a supplier", "Consultant", "10", "£50,000,000 & above", "Gold", "\"\"", "Acclaim", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
